# Generated by Django 2.2.5 on 2020-01-10 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_rideraccount_django_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideraccount',
            name='django_account',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
