# Generated by Django 2.2.5 on 2020-01-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_auto_20200110_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiderAccount',
        ),
    ]
