# Generated by Django 2.2.5 on 2020-01-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=16, unique=True)),
                ('display_name', models.CharField(default=None, max_length=32, unique=True)),
            ],
        ),
    ]
