# Generated by Django 2.2.5 on 2020-01-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0007_appuser_pronoun'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_name', models.CharField(default=None, max_length=64, unique=True)),
                ('start_address', models.CharField(default=None, max_length=128, unique=True)),
                ('start_place_id', models.CharField(default=None, max_length=256, unique=True)),
                ('end_name', models.CharField(default=None, max_length=64, unique=True)),
                ('end_address', models.CharField(default=None, max_length=128, unique=True)),
                ('end_place_id', models.CharField(default=None, max_length=256, unique=True)),
                ('ride_utc', models.IntegerField(default=None)),
            ],
        ),
    ]
