# Generated by Django 2.2.5 on 2020-01-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0008_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='csrf_token',
            field=models.CharField(default=None, max_length=256, unique=True),
        ),
    ]
