# Generated by Django 2.2.5 on 2020-01-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0011_delete_rideshareuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='pronoun',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='rideshare.Pronoun'),
        ),
    ]
