# Generated by Django 2.2.5 on 2020-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0012_auto_20200123_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=16, unique=True)),
                ('display_name', models.CharField(default=None, max_length=32, unique=True)),
            ],
        ),
    ]
