# Generated by Django 2.2.5 on 2020-01-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0014_appuser_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='accommodation',
        ),
    ]
