# Generated by Django 2.2.5 on 2020-01-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0015_remove_appuser_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='accommodations',
            field=models.ManyToManyField(to='rideshare.Accommodation'),
        ),
    ]
