# Generated by Django 2.2.5 on 2020-01-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0016_appuser_accommodations'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='icon',
            field=models.CharField(default='', max_length=64),
        ),
    ]
