# Generated by Django 2.2.5 on 2020-01-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0017_auto_20200125_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_address',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
