# Generated by Django 2.2.5 on 2020-01-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0018_auto_20200125_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='email_verified',
        ),
    ]
