# Generated by Django 2.2.5 on 2020-01-25 23:34

from django.db import migrations, models
import rowsheet.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0020_auto_20200125_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone_verification_code',
            field=models.CharField(default=rowsheet.utils.random_phone_code, max_length=32),
        ),
    ]
