# Generated by Django 2.2.5 on 2020-01-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0021_appuser_phone_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='69GSQ7IF5L4K3Q5NEAG3VV5EIWWQM4NAU00GP7FXB3YQWYZYF3UZQ47OEU4IRM75', max_length=100),
        ),
    ]
