# Generated by Django 2.2.5 on 2020-02-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0027_auto_20200202_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldRideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('end_location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pickup_time', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pronoun', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('start_location', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('num_bags', models.IntegerField(default=None)),
                ('passenger_count', models.IntegerField(default=None)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='1HRKS3HEBL04NETNJCRC5TGM37XSM64O1E0WOZQFWU8FSEZ14YJRIY005WPQMGQK', max_length=100),
        ),
    ]
