# Generated by Django 2.2.5 on 2020-02-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0028_auto_20200204_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='OldRideRequest',
            name='special_req',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='BH471X2VAK4LME004ZFPWB9P3XU1G1KT4UVPKB5L1KMQX14I1EC1NHSM8Z024GJ2', max_length=100),
        ),
        migrations.AlterField(
            model_name='OldRideRequest',
            name='start_location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
