# Generated by Django 2.2.5 on 2020-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0030_auto_20200204_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldriderequest',
            name='pickup_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='F3408O22BBTGVOWO9CX4D7VP0QFTZU95MS3PN8I5HJRB92JK6BIK74JA3I2TEKTW', max_length=100),
        ),
    ]
