# Generated by Django 2.2.5 on 2020-02-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0032_auto_20200204_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldDriverSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pronoun', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('smartphone_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vehicle_doors', models.IntegerField(default=None)),
                ('vehicle_make', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vehicle_model', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vehicle_year', models.IntegerField(default=None)),
                ('yes_no_criminal_history', models.BooleanField(default=False)),
                ('yes_no_insurance', models.BooleanField(default=False)),
                ('yes_no_square', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='KWC5BW46DMAS8X70464NYNPLCYXGRTMZKJGG2RRLH2O3KND9C158XYCIKOBAG9NI', max_length=100),
        ),
    ]
