# Generated by Django 2.2.5 on 2020-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0033_auto_20200204_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddriversignup',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='RO7HL0ZV363358SRQ7BIQQFOJWIWG8R3JWATPCN9E5TIUDC2WVZVLEJZ14G6C03T', max_length=100),
        ),
    ]
