# Generated by Django 2.2.5 on 2020-02-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0034_auto_20200204_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddriversignup',
            name='contact_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='olddriversignup',
            name='contact_phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='S8W2BXE7K3YBV1WI2H1FMCKEOXGY74G39E7IQV4KG69WASH1KEQ6USVMCBMSL7EA', max_length=100),
        ),
    ]
