# Generated by Django 2.2.3 on 2020-03-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0035_auto_20200204_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'verbose_name': 'Accomodation', 'verbose_name_plural': 'Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Homobiles Team Member', 'verbose_name_plural': 'Homobiles Team Members'},
        ),
        migrations.AlterModelOptions(
            name='olddriversignup',
            options={'verbose_name': 'Driver Application', 'verbose_name_plural': 'Driver Applications'},
        ),
        migrations.AlterModelOptions(
            name='oldriderequest',
            options={'verbose_name': 'Current Ride Request', 'verbose_name_plural': 'Current Ride Requests'},
        ),
        migrations.AlterModelOptions(
            name='pronoun',
            options={'verbose_name': 'Pronoun', 'verbose_name_plural': 'Pronouns'},
        ),
        migrations.AlterModelOptions(
            name='riderequest',
            options={'verbose_name': 'Rider Request (development)', 'verbose_name_plural': 'Rider Requests (development)'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='accommodations',
            field=models.ManyToManyField(default=None, to='rideshare.Accommodation'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='08S7IJ09RSLYB4TSZW6A8TFR7LRIBMQKHCDTL7Z2HBHVG29IEN6D8SWWLIV73LZ3', max_length=100),
        ),
    ]
