# Generated by Django 2.2.5 on 2020-03-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0036_auto_20200305_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='accommodations',
            field=models.ManyToManyField(to='rideshare.Accommodation'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='XRZFL83KYYTOW5H2MDASKTHP0I51T7JEF9640VKY5B3P53L852TUSU9TKRQQWQW5', max_length=100),
        ),
    ]
