# Generated by Django 2.2.3 on 2020-03-07 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0036_auto_20200305_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='accommodations',
            field=models.ManyToManyField(to='rideshare.Accommodation'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='TTWE6ZRS0HVQHMJ8JK5SINDM8DORAVSI8L4CI12AS2JBZEJA4OJ37OI8DK1WHXEO', max_length=100),
        ),
        migrations.AlterField(
            model_name='olddriversignup',
            name='contact_email',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='olddriversignup',
            name='contact_phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10-12 digit phone number.', regex='^([1-9])+?1?\\d{10,12}$')]),
        ),
        migrations.AlterField(
            model_name='oldriderequest',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10-12 digit phone number.', regex='^([1-9])+?1?\\d{10,12}$')]),
        ),
    ]
