# Generated by Django 2.2.5 on 2020-03-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0037_auto_20200307_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='csrf_token',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='end_name',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='ride_utc',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='start_name',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='LROTFAWYA193258E59ZU5INIKHW9012OYSAPDV3IALKT6FF279F6I0JI4F1NSWI1', max_length=100),
        ),
    ]
