# Generated by Django 2.2.5 on 2020-03-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0038_auto_20200307_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='pickup_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='QCUFUKETYLBSDTDYTC8PQD29PFI6J23WQA4JZ1F1MIRYSNXDFPM8PQCW2T52JHVT', max_length=100),
        ),
    ]
