# Generated by Django 2.2.5 on 2020-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0039_auto_20200307_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='RLE5IR3Z3E1YYK0YGY1ILKREQWV3UX22SRECMAN9221HKRZZQF1RUWIIPSBTBBLL', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='pickup_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
