# Generated by Django 2.2.5 on 2020-03-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0040_auto_20200307_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='in_setup',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='H76XGC27SMY1UL06YLM61DMHXP00ZWR2P924ZDU8OAL3BDIJKK4ACAXGTHSZYPTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='app_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rideshare.AppUser'),
        ),
        migrations.AlterUniqueTogether(
            name='riderequest',
            unique_together={('app_user', 'in_setup')},
        ),
    ]
