# Generated by Django 2.2.5 on 2020-03-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0038_auto_20200307_1214'),
        ('rideshare', '0041_auto_20200307_1121'),
    ]

    operations = [
    ]
