# Generated by Django 2.2.3 on 2020-03-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0042_merge_20200307_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='0PW3HR8XWK7S7ZZCWGDTHH0AXG4V1Y7YOY9R4K78NIK84G2G6VOEMGOLSS7QUWGT', max_length=100),
        ),
    ]
