# Generated by Django 2.2.3 on 2020-03-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0043_auto_20200309_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='97FJHQZUUYFUF5UHWNLTTALEIZ6QBVHQE9ZVKS3O6V3CW5LRZ13R4AMDA5AUMZEJ', max_length=100),
        ),
    ]
