# Generated by Django 2.2.3 on 2020-03-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0044_auto_20200310_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='MF355A161A5QHYIA57DF907APNXIA8WNXYNGG6I01PQPADUQQLCCC9OEL654HMKR', max_length=100),
        ),
    ]
