# Generated by Django 2.2.5 on 2020-03-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0045_auto_20200310_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='driver_status',
            field=models.CharField(blank=True, choices=[('RS_1_D', 'RS_1_D'), ('RS_2_D', 'RS_2_D'), ('RS_3_D', 'RS_3_D'), ('RS_8_D', 'RS_8_D'), ('RS_9_D', 'RS_9_D'), ('RS_10_D', 'RS_10_D')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='passenger_status',
            field=models.CharField(blank=True, choices=[('RS_1_P', 'RS_1_P'), ('RS_4_P', 'RS_4_P'), ('RS_5_P', 'RS_5_P'), ('RS_7_P', 'RS_7_P'), ('RS_10_P', 'RS_10_P')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='WHC60V33XLJ68UMFX56RIX8OR5M3YUVU0RBE8N3H5EVY2BR9K0P15HWMWR79K4IX', max_length=100),
        ),
    ]
