# Generated by Django 2.2.3 on 2020-03-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0045_auto_20200310_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='WXB73WME3GDCQ7QGQJNYBERAI3S669Y96PWNDHYU0MWNS7W7VJHSSG86ILOWVBT9', max_length=100),
        ),
    ]
