# Generated by Django 2.2.5 on 2020-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0046_auto_20200310_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='5I964UHNNR63Z21P9PL2IVYIHYEL181LWL908MF1EFY60PSKZQ4Q22CG6H4POROF', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(blank=True, choices=[('REQ_1', 'REQ_1'), ('REQ_2', 'REQ_2'), ('REQ_3', 'REQ_3'), ('REQ_4', 'REQ_4'), ('REQ_5', 'REQ_5'), ('REQ_X', 'REQ_X')], default=None, max_length=32, null=True),
        ),
    ]
