# Generated by Django 2.2.5 on 2020-03-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0047_auto_20200310_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='29Q660IZYPOKPHHH1N8VTJRM946O3PULZUUY5MZX3PQHTJ5L4L37BYWIG7GN97SW', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='in_setup',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
