# Generated by Django 2.2.5 on 2020-03-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0048_auto_20200310_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='2GAF8EDUYVDR54XHKYHBL0YTWNZZTE3KG4RZLHVD98RRPZHJX9EOSSY0MDYFUGKY', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='end_address',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='end_place_id',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='start_address',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='start_place_id',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
