# Generated by Django 2.2.5 on 2020-03-11 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0049_auto_20200310_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='app_user_driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_user_driver', to='rideshare.AppUser'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='ASVIY16V54KD89WW5E8Z2O2WTFFPAJO7Y9UZ5HL1P2EDEG3RXBFIU8172P6ZASGK', max_length=100),
        ),
    ]
