# Generated by Django 2.2.5 on 2020-03-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0050_auto_20200311_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='driver_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='ZR1AXM844GSENP9RXUWQ7H13PELFCH0YUJ49AZT7M00Z79TM0DQ15HIPCY6C06ES', max_length=100),
        ),
    ]
