# Generated by Django 2.2.3 on 2020-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0051_auto_20200311_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='R311ZUO7PUOS4JYNKUEE9APL6IQH2N3BG0XOJBIVWRK0DE81YHH68V75C291UC0X', max_length=100),
        ),
    ]
