# Generated by Django 2.2.5 on 2020-03-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0055_auto_20200311_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsubscription',
            name='product_id',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='YHATABBDJFRIPVVWH2EUP82TSEJ6U37B6K8OURCHEIMWFT4A91PPC1JT723Y492E', max_length=100),
        ),
        migrations.AlterField(
            model_name='donationsubscription',
            name='checkout_session_id',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='donationsubscription',
            name='plan_id',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
