# Generated by Django 2.2.5 on 2020-03-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0056_auto_20200311_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationsubscription',
            old_name='inverval',
            new_name='interval',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='UXG2M2AMWU14RT1Z6KJIQBMG57DGECI9OCLBZ67AUY5TEL9Y6CMVUYEOHSWJREST', max_length=100),
        ),
    ]
