# Generated by Django 2.2.5 on 2020-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0057_auto_20200311_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='DNKW80EINAGBI26D7NWUYG8Z8YHWJW7KN3XKC3QRAJ803GVOJLEJT4WU0QKGZ0K7', max_length=100),
        ),
        migrations.AlterField(
            model_name='donationsubscription',
            name='amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
