# Generated by Django 2.2.5 on 2020-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0058_auto_20200311_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsubscription',
            name='subscription_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='4UUABWN6Z62KE6GGYGOOQ3TCNV1DYCVG8ZQZ2MGFPP7E1HV0SS6Q3KAUVSUWOMLX', max_length=100),
        ),
    ]
