# Generated by Django 2.2.5 on 2020-03-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0059_auto_20200311_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsubscription',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='2D1A3BAP10XS0FT0BLM5WX3191FS4J10DYGTQAM1TPN4MASIPLXOGUJR0KKICC7Q', max_length=100),
        ),
    ]
