# Generated by Django 2.2.5 on 2020-03-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0060_auto_20200313_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(default=None, max_length=500)),
                ('checkout_session_id', models.CharField(default=None, max_length=500)),
                ('amount', models.IntegerField(blank=True, default=None, null=True)),
                ('currency', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('success', models.BooleanField(blank=True, default=False, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='8XFKG49TRP3O3NW4X3L42L037346J5I07SNWJ8R7LPHFBTBZZPVTIKAQP5S4SXEY', max_length=100),
        ),
    ]
