# Generated by Django 2.2.5 on 2020-03-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0061_auto_20200317_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='ride_donation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rideshare.RideDonation'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='UP770AA1D02X1AZI98CBY85ZPLE0Q5SVUX7UPJMA88CN9KVNSGTMLSVNUADU9SAI', max_length=100),
        ),
    ]
