# Generated by Django 2.2.5 on 2020-03-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0062_auto_20200317_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='ride_donation',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='CT3BECXKW2K0OX4HLWJM7UKXWV6TWOC4A5QY3RS7WA5S6WVWZQLTTXVMR4DG550L', max_length=100),
        ),
    ]
