# Generated by Django 2.2.3 on 2020-03-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0064_auto_20200317_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='JUGH21V3PIF4RZE1GZPOJ9R98ZQXX6KFJF63ZQ94WV4Q0QY6PJ95NBYF6L1GN7L6', max_length=100),
        ),
    ]
