# Generated by Django 2.2.5 on 2020-03-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0065_auto_20200320_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='1MDU5DHDXVFAX09GJXEG7J8RG5QJAW9UJMZNINO1NZGTR96V0P15Y1HP6UWNAKPA', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='suggested_donation',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
