# Generated by Django 2.2.5 on 2020-03-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0065_auto_20200319_0729'),
        ('rideshare', '0066_auto_20200320_1959'),
    ]

    operations = [
    ]
