# Generated by Django 2.2.3 on 2020-03-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0067_merge_20200320_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='TZOZK6ZTMWSEY8GQQTP7B7Z4Y3IQPSZOYPSBD4SAADPJZTVSGSMS3XJQW2SZYHO0', max_length=100),
        ),
    ]
