# Generated by Django 2.2.3 on 2020-03-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0046_auto_20200310_0425'),
        ('rideshare', '0068_auto_20200320_2213'),
    ]

    operations = [
    ]
