# Generated by Django 2.2.5 on 2020-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0069_merge_20200320_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='color_code',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='number_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='PZ5EX58BCG3KDAHBCOOMRBP06E5R0K2SGCTRTZW5AJ1J71CZ800BLSQHQR74ZX5L', max_length=100),
        ),
    ]
