# Generated by Django 2.2.3 on 2020-03-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0069_merge_20200320_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email_verification_code',
            field=models.CharField(default='0CUMFZ92SRFTKU4B64GYN4N6DUGQA1TAXO7Z5WJNJZOE6RMZU1K3KQZYGKND0FDF', max_length=100),
        ),
    ]
