# Generated by Django 2.2.3 on 2020-03-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0070_auto_20200320_2323'),
        ('rideshare', '0070_auto_20200321_1727'),
    ]

    operations = [
    ]
